import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { toolQuestions } from "@/data/toolQuestions";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { cn } from "@/lib/utils";
import { ArrowLeft, ArrowRight, CheckCircle2, RotateCcw, FileText, Download } from "lucide-react";
import { Textarea } from "@/components/ui/textarea";

export const Wizard = () => {
    const navigate = useNavigate();
    const [currentPhaseIndex, setCurrentPhaseIndex] = useState(0);
    const [currentStepIndex, setCurrentStepIndex] = useState(0);
    // Updated state to hold array of strings for multi-select
    const [answers, setAnswers] = useState<Record<string, string[]>>({});
    const [qualitativeInput, setQualitativeInput] = useState("");
    const [showQualitativeStep, setShowQualitativeStep] = useState(false);
    const [isCompleted, setIsCompleted] = useState(false);

    const currentPhase = toolQuestions[currentPhaseIndex];
    const currentStep = currentPhase.steps[currentStepIndex];
    const headerTitle = "Infinif.ai Business Scan";

    const totalSteps = toolQuestions.reduce((acc, phase) => acc + phase.steps.length, 0);
    const currentGlobalStep = toolQuestions.slice(0, currentPhaseIndex).reduce((acc, phase) => acc + phase.steps.length, 0) + currentStepIndex + 1;
    // Add 1 to totalSteps for the qualitative input step in progress calculation
    const progress = showQualitativeStep
        ? 100
        : ((currentGlobalStep - 1) / (totalSteps + 1)) * 100;

    const handleOptionSelect = (value: string) => {
        setAnswers(prev => {
            const currentAnswers = prev[currentStep.id] || [];
            if (currentAnswers.includes(value)) {
                return { ...prev, [currentStep.id]: currentAnswers.filter(v => v !== value) };
            } else {
                return { ...prev, [currentStep.id]: [...currentAnswers, value] };
            }
        });
    };

    const handleNext = () => {
        if (currentStepIndex < currentPhase.steps.length - 1) {
            setCurrentStepIndex(prev => prev + 1);
        } else if (currentPhaseIndex < toolQuestions.length - 1) {
            setCurrentPhaseIndex(prev => prev + 1);
            setCurrentStepIndex(0);
        } else {
            // All questions answered, go to Qualitative Step
            setShowQualitativeStep(true);
        }
    };

    const handleFinish = () => {
        setShowQualitativeStep(false);
        setIsCompleted(true);
    };

    const handleBack = () => {
        if (showQualitativeStep) {
            setShowQualitativeStep(false);
            return;
        }

        if (currentStepIndex > 0) {
            setCurrentStepIndex(prev => prev - 1);
        } else if (currentPhaseIndex > 0) {
            setCurrentPhaseIndex(prev => prev - 1);
            setCurrentStepIndex(toolQuestions[currentPhaseIndex - 1].steps.length - 1);
        }
    };

    const handleRestart = () => {
        setAnswers({});
        setQualitativeInput("");
        setCurrentPhaseIndex(0);
        setCurrentStepIndex(0);
        setShowQualitativeStep(false);
        setIsCompleted(false);
    };

    const handlePrint = () => {
        window.print();
    };

    // --- RENDER COMPLETED REPORT ---
    if (isCompleted) {
        return (
            <div className="max-w-5xl mx-auto py-12 px-4 animate-in fade-in duration-500">
                <Card className="bg-background border-border shadow-2xl overflow-hidden relative print:shadow-none print:border-none">
                    <div className="absolute top-0 left-0 w-full h-2 bg-gradient-to-r from-accent to-primary print:hidden" />
                    <CardContent className="p-8 md:p-12">

                        {/* Report Header */}
                        <div className="flex justify-between items-start mb-12 border-b border-border/50 pb-6">
                            <div>
                                <h1 className="text-4xl font-bold text-foreground mb-2">AI Strategy Report</h1>
                                <p className="text-xl text-muted-foreground">Generated by infinif.ai</p>
                            </div>
                            <div className="text-right hidden sm:block">
                                <p className="text-sm text-muted-foreground">{new Date().toLocaleDateString()}</p>
                                <p className="text-sm font-bold text-accent">CONFIDENTIAL</p>
                            </div>
                        </div>

                        {/* Executive Summary */}
                        <div className="mb-12">
                            <h2 className="text-2xl font-bold text-primary mb-4 flex items-center">
                                <FileText className="w-6 h-6 mr-2" />
                                Executive Summary
                            </h2>
                            <div className="bg-secondary/10 p-6 rounded-xl border border-secondary/20">
                                <p className="text-lg leading-relaxed whitespace-pre-line mb-4">
                                    {qualitativeInput || "No specific comments provided."}
                                </p>
                                <p className="text-muted-foreground italic">
                                    Based on the responses, the organization shows a distinct need for structured AI implementation focusing on specific key areas identified below.
                                </p>
                            </div>
                        </div>

                        {/* Detailed Recommendations */}
                        <div className="mb-12">
                            <h2 className="text-2xl font-bold text-accent mb-6">Strategic Recommendations</h2>
                            <div className="grid grid-cols-1 gap-6">
                                {toolQuestions.map(phase => (
                                    <div key={phase.id} className="space-y-4">
                                        <h3 className="text-lg font-bold uppercase tracking-wider text-muted-foreground border-b border-border/50 pb-2">{phase.phase} Phase</h3>
                                        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                                            {phase.steps.map(step => {
                                                const selectedValues = answers[step.id] || [];
                                                // Find selected options to get their recommendations
                                                const recommendations = step.options
                                                    .filter(opt => selectedValues.includes(opt.value))
                                                    .map(opt => opt.recommendation);

                                                if (recommendations.length === 0) return null;

                                                return (
                                                    <div key={step.id} className="bg-card border border-border/50 p-4 rounded-lg break-inside-avoid">
                                                        <h4 className="font-bold text-foreground mb-2 flex items-center">
                                                            <span className="w-6 h-6 rounded-full bg-primary/10 text-primary flex items-center justify-center text-xs mr-2">{step.letter}</span>
                                                            {step.title}
                                                        </h4>
                                                        <ul className="list-disc list-inside space-y-1">
                                                            {recommendations.map((rec, i) => (
                                                                <li key={i} className="text-sm text-muted-foreground">{rec}</li>
                                                            ))}
                                                        </ul>
                                                    </div>
                                                );
                                            })}
                                        </div>
                                    </div>
                                ))}
                            </div>
                        </div>

                        {/* Contact Details (Visible in Print/Report) */}
                        <div className="mt-12 pt-8 border-t border-border/50 break-inside-avoid">
                            <h2 className="text-2xl font-bold text-foreground mb-6">Contact Details</h2>
                            <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
                                <div className="space-y-4">
                                    <div>
                                        <p className="font-bold text-muted-foreground uppercase text-xs tracking-wider">Email</p>
                                        <p className="text-lg">bjorn@infinif.ai</p>
                                    </div>
                                    <div>
                                        <p className="font-bold text-muted-foreground uppercase text-xs tracking-wider">Phone</p>
                                        <p className="text-lg">+31 6 1115 9651</p>
                                    </div>
                                    <div>
                                        <p className="font-bold text-muted-foreground uppercase text-xs tracking-wider">Address</p>
                                        <p className="text-lg">Ericaweg 47, 1272CS Huizen</p>
                                    </div>
                                </div>
                                <div className="space-y-4">
                                    <div>
                                        <p className="font-bold text-muted-foreground uppercase text-xs tracking-wider">Company Details</p>
                                        <p className="text-base text-muted-foreground">KvK: 97606952</p>
                                        <p className="text-base text-muted-foreground">BTW: NL005278494B56</p>
                                    </div>
                                    <div className="pt-2">
                                        <p className="text-sm text-muted-foreground italic">
                                            Ready to infinif.ai your business? Let's discuss your custom implementation plan.
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>

                        {/* Action Buttons (Hidden in Print) */}
                        <div className="flex flex-col sm:flex-row gap-4 justify-center print:hidden mt-12 bg-secondary/5 p-8 rounded-2xl">
                            <Button size="lg" className="h-12 px-8 text-lg rounded-full shadow-lg shadow-primary/20" onClick={() => navigate('/#contact')}>
                                Plan Appointment
                            </Button>
                            <Button variant="outline" size="lg" className="h-12 px-8 text-lg rounded-full" onClick={handlePrint}>
                                <Download className="w-4 h-4 mr-2" />
                                Download Report (PDF)
                            </Button>
                            <Button variant="ghost" size="lg" className="h-12 px-8 text-lg rounded-full" onClick={handleRestart}>
                                <RotateCcw className="w-4 h-4 mr-2" />
                                Start Over
                            </Button>
                        </div>
                    </CardContent>
                </Card>
            </div>
        );
    }

    // --- RENDER QUALITATIVE INPUT STEP ---
    if (showQualitativeStep) {
        return (
            <div className="max-w-2xl mx-auto py-12 px-4">
                <Card className="bg-background/80 backdrop-blur-xl border-border shadow-2xl">
                    <CardHeader>
                        <CardTitle className="text-2xl">Almost there...</CardTitle>
                        <CardDescription>Please describe your specific context or needs to finalize the report.</CardDescription>
                    </CardHeader>
                    <CardContent className="space-y-6">
                        <div className="space-y-2">
                            <label className="text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70">
                                Additional Comments / Context
                            </label>
                            <Textarea
                                placeholder="E.g., We are looking to automate customer support but have security concerns..."
                                className="min-h-[200px] text-lg p-4"
                                value={qualitativeInput}
                                onChange={(e) => setQualitativeInput(e.target.value)}
                            />
                        </div>
                        <div className="flex justify-between pt-4">
                            <Button variant="ghost" onClick={handleBack}>Back</Button>
                            <Button onClick={handleFinish} className="bg-accent hover:bg-accent/90 text-white">
                                Generate Report <FileText className="w-4 h-4 ml-2" />
                            </Button>
                        </div>
                    </CardContent>
                </Card>
            </div>
        )
    }

    // --- RENDER WIZARD QUESTIONS ---
    const Icon = currentStep.icon;

    return (
        <div className="max-w-5xl mx-auto py-8 md:py-16 px-4">
            {/* Header / Progress */}
            <div className="mb-12">
                <div className="flex justify-between items-end mb-4">
                    <div>
                        <h1 className="text-3xl font-bold bg-clip-text text-transparent bg-gradient-to-r from-primary to-accent mb-2">
                            {headerTitle}
                        </h1>
                        <p className="text-muted-foreground font-medium">
                            Phase {currentPhaseIndex + 1}: <span className="text-foreground font-bold">{currentPhase.phase}</span>
                        </p>
                    </div>
                    <div className="text-right">
                        <span className="text-4xl font-black text-secondary/30">{currentStep.letter}</span>
                    </div>
                </div>
                <div className="h-2 w-full bg-secondary/20 rounded-full overflow-hidden">
                    <div
                        className="h-full bg-gradient-to-r from-accent to-primary transition-all duration-500 ease-out"
                        style={{ width: `${progress}%` }}
                    />
                </div>
            </div>

            {/* Main Card */}
            <div className="relative perspective-1000">
                <Card className="bg-background/80 backdrop-blur-xl border-border shadow-2xl overflow-hidden min-h-[400px] flex flex-col transition-all duration-500">
                    <CardContent className="p-8 md:p-12 flex-grow flex flex-col">

                        <div className="flex items-center gap-4 mb-8">
                            <div className="w-14 h-14 rounded-2xl bg-primary/10 flex items-center justify-center shrink-0">
                                <Icon className="w-7 h-7 text-primary" />
                            </div>
                            <div>
                                <h2 className="text-2xl font-bold">{currentStep.title}</h2>
                                <p className="text-muted-foreground">{currentStep.question}</p>
                                <p className="text-xs text-muted-foreground mt-1 uppercase tracking-wider font-semibold">Select all that apply</p>
                            </div>
                        </div>

                        <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mt-auto">
                            {currentStep.options.map((option, idx) => {
                                const isSelected = (answers[currentStep.id] || []).includes(option.value);
                                return (
                                    <button
                                        key={idx}
                                        onClick={() => handleOptionSelect(option.value)}
                                        className={cn(
                                            "p-6 rounded-xl border-2 text-left transition-all duration-200 hover:scale-[1.02] active:scale-[0.98]",
                                            isSelected
                                                ? "border-accent bg-accent/5 shadow-md shadow-accent/10"
                                                : "border-border/50 bg-card hover:border-primary/50 hover:bg-secondary/5"
                                        )}
                                    >
                                        <div className="flex items-center justify-between">
                                            <span className={cn("font-medium", isSelected ? "text-accent" : "text-foreground")}>
                                                {option.label}
                                            </span>
                                            {isSelected && <CheckCircle2 className="w-5 h-5 text-accent" />}
                                        </div>
                                    </button>
                                );
                            })}
                        </div>

                    </CardContent>

                    {/* Footer Nav */}
                    <div className="p-6 border-t border-border/50 flex justify-between bg-secondary/5">
                        <Button
                            variant="ghost"
                            onClick={handleBack}
                            disabled={!showQualitativeStep && currentGlobalStep === 1}
                            className="hover:bg-background/50"
                        >
                            <ArrowLeft className="w-4 h-4 mr-2" />
                            Back
                        </Button>
                        <Button
                            onClick={handleNext}
                            // Allow next if at least one option is selected
                            disabled={!(answers[currentStep.id] && answers[currentStep.id].length > 0)}
                            className="rounded-full px-8 bg-primary hover:bg-primary/90 text-white shadow-lg shadow-primary/20"
                        >
                            {currentPhaseIndex === toolQuestions.length - 1 && currentStepIndex === currentPhase.steps.length - 1 ? "Next: Finalize" : "Next Step"}
                            <ArrowRight className="w-4 h-4 ml-2" />
                        </Button>
                    </div>
                </Card>
            </div>

            {/* Background Orbs simulating 'AI' */}
            <div className="fixed top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-full h-full max-w-7xl -z-10 pointer-events-none opacity-30 overflow-hidden">
                <div className="absolute top-0 right-0 w-[600px] h-[600px] bg-accent/20 rounded-full blur-[120px] animate-pulse" />
                <div className="absolute bottom-0 left-0 w-[600px] h-[600px] bg-primary/20 rounded-full blur-[120px] animate-pulse delay-75" />
            </div>
        </div>
    );
};
